# Generated by Django 5.0.7 on 2026-07-25 12:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="name")),
                ("codename", models.CharField(max_length=100, unique=True, verbose_name="codename")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("module", models.CharField(blank=True, max_length=50, verbose_name="module")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True, verbose_name="email address")),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[common.validators.PhoneValidator()],
                        verbose_name="phone number",
                    ),
                ),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/", verbose_name="avatar")),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[common.validators.EmployeeIDValidator()],
                        verbose_name="employee ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, verbose_name="department")),
                ("position", models.CharField(blank=True, max_length=100, verbose_name="position")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMINISTRATOR", "Administrator"),
                            ("WAREHOUSE_MANAGER", "Warehouse Manager"),
                            ("WAREHOUSE_OPERATOR", "Warehouse Operator"),
                            ("MAINTENANCE_MANAGER", "Maintenance Manager"),
                            ("TECHNICIAN", "Technician"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="VIEWER",
                        max_length=30,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DEACTIVATED", "Deactivated"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "invitation_token",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name="invitation token"
                    ),
                ),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="invitation sent at")),
                (
                    "invitation_accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="invitation accepted at"),
                ),
                ("terms_accepted", models.BooleanField(default=False, verbose_name="terms accepted")),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="terms accepted at")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                ("login_time", models.DateTimeField(auto_now_add=True, verbose_name="login time")),
                ("logout_time", models.DateTimeField(blank=True, null=True, verbose_name="logout time")),
                ("status", models.CharField(default="SUCCESS", max_length=20, verbose_name="status")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "login history",
                "verbose_name_plural": "login histories",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMINISTRATOR", "Administrator"),
                            ("WAREHOUSE_MANAGER", "Warehouse Manager"),
                            ("WAREHOUSE_OPERATOR", "Warehouse Operator"),
                            ("MAINTENANCE_MANAGER", "Maintenance Manager"),
                            ("TECHNICIAN", "Technician"),
                            ("VIEWER", "Viewer"),
                        ],
                        max_length=30,
                        verbose_name="role",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "role permission",
                "verbose_name_plural": "role permissions",
                "ordering": ["role", "permission"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="accounts_us_employe_0cbd94_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="accounts_us_status_6bbe13_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
    ]
